name: Bicep Deploy Test

on:
  push:
    branches: [ feature/bicep-pipeline ]
   
jobs:
  deploy-infrastructure:
    name: Deploy infrastructure
    runs-on: ubuntu-latest
    steps:

      # Check out the repository 
      - uses: actions/checkout@v3
        name: Checkout repository
        with:
          lfs: true
      
      # Login to Azure
      - uses: azure/login@v1
        name: Login to Azure
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
