name: Bicep Deploy Test

on:
  push:
    branches: [ feature/bicep-pipeline ]
  workflow_dispatch:
   
jobs:
  deploy-infrastructure:
    name: Deploy infrastructure
    runs-on: ubuntu-latest
    environment: Test
    steps:

      # Check out the repository 
      - uses: actions/checkout@v3
        name: Checkout repository
        with:
          lfs: true
      
      # Login to Azure
      - uses: azure/login@v1
        name: Login to Azure
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
