name: Bicep Deploy Test

on:
  push:
    branches: [feature/bicep-pipeline]

permissions:
  id-token: write
  contents: read

env:
  RESOURCE_GROUP: OhMyWord-Test

jobs:
  deploy-infrastructure:
    name: Deploy infrastructure
    runs-on: ubuntu-latest
    environment: Test
    steps:
      # Check out the repository
      - uses: actions/checkout@v3
        name: Checkout repository
        with:
          lfs: true

      # Login to Azure
      - uses: azure/login@v1
        name: Login to Azure
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      # Deploy Bicep template
      - name: Deploy Bicep template
        working-directory: ./Infrastructure
        run: az deployment group create --resource-group $RESOURCE_GROUP --template-file main.bicep

  build-app:
    name: Build application
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Checkout repository
        with:
          lfs: true
          
      - uses: ./.github/workflows/build-app.yml
