name: Bicep Deploy Test

# subscription: d38de57b-b6cc-4a43-aeac-c7e6b68f1283
# resource-group: OhMyWord-Dev
# scopes: --scopes /subscriptions/d38de57b-b6cc-4a43-aeac-c7e6b68f1283/resourceGroups/OhMyWord-Dev

on:
  push:
    branches:
      - bicep-pipeline
  workflow_dispatch:
   
jobs:
  deploy-infrastructure:
    name: Deploy infrastructure
    runs-on: ubuntu-latest
    steps:

      # Check out the repository 
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          lfs: true
      
      # Login to Azure
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
