on:
  workflow_call:
    inputs:
      build_configuration:
        required: true
        type: string

jobs:
  build-publish:
    runs-on: ubuntu-latest
    name: Build and publish
    env:
      BUILD_CONFIGURATION: ${{ inputs.build_configuration }}}
    steps:
      # Checkout the repository
      - uses: actions/checkout@v3
        name: Checkout repository
        with:
          submodules: true

      # Setup Node environment
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      # Install Angular CLI globally
      - name: Install Angular CLI
        run: npm install -g @angular/cli

      # Install dependencies
      - name: Install project dependencies
        working-directory: ./FrontEnd
        run: npm install

      # Build the client
      - name: Build client application
        working-directory: ./FrontEnd
        run: ng build --configuration $BUILD_CONFIGURATION

      # Copy static web app config
      - name: Copy static web app config
        run: cp ./FrontEnd/staticwebapp.config.json ./FrontEnd/dist

      # Upload build artifact
      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: frontend-app
          path: ./FrontEnd/dist
