on:
  workflow_call:

jobs:
  build:
    name: Build and publish
    runs-on: ubuntu-latest
    env:
      BUILD_CONFIGURATION: Release
      PUBLISH_DIRECTORY: /tmp/app
    steps:
      # Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Build project
      - name: Build solution
        working-directory: ./BackEnd/Functions
        run: dotnet build --configuration $BUILD_CONFIGURATION --output $PUBLISH_DIRECTORY

      # Upload published application artifact
      - name: Upload published application artifact
        uses: actions/upload-artifact@v3
        with:
          name: functions-app
          path: ${{ env.PUBLISH_DIRECTORY }}
