name: CI/CD Application

on:
  push:
    branches:
      - main

jobs:
  build-client:
    name: Build client
    runs-on: ubuntu-latest
    steps:
      # Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          lfs: true

      # Setup Node environment
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      # Install dependencies
      - name: Install dependencies
        working-directory: ./Client
        run: npm ci

      # Build the client
      - name: Build client application
        working-directory: ./Client
        run: npm run build

      # Upload build artifact
      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: client-build
          path: ./Client/dist

  build-app:
    name: Build application
    runs-on: ubuntu-latest
    needs: build-client
    steps:
      # Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          lfs: true

      # Download client build artifact
      - name: Download client build artifact
        uses: actions/download-artifact@v3
        with:
          name: client-build
          path: ./Api/wwwroot

      # Setup .NET environment
      - name: Set up .NET Core
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: "6.0.x"
          include-prerelease: true

      # Build solution
      - name: Build solution
        run: dotnet build --configuration Release

      # Test solution
      - name: Test solution
        run: dotnet test --configuration Release --logger trx --results-directory TestResults

      # Publish application
      - name: Publish application
        working-directory: ./Api
        run: dotnet publish --configuration Release --output ${{env.DOTNET_ROOT}}/app

      # Upload published application artifact
      - name: Upload published application artifact
        uses: actions/upload-artifact@v3
        with:
          name: published-app
          path: ${{env.DOTNET_ROOT}}/app

  deploy:
    name: Deploy application
    runs-on: ubuntu-latest
    needs: build-app
    environment:
      name: Production
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      # Download published application from build job
      - name: Download published application artifact
        uses: actions/download-artifact@v3
        with:
          name: published-app

      # Deploy to Azure app service
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: app-ohmyword-prod
          slot-name: Production
          publish-profile: ${{ secrets.AZURE_APPSERVICE_PUBLISH_PROFILE }}
          package: .
