name: CI/CD Application

on:
  push:
    branches:
      - main
      - develop
    paths:
      - .github/workflows/cicd-app.yml
      - FrontEnd/**
      - BackEnd/**
      - Deployment/**

  pull_request:
    branches:
      - main
    paths:
      - .github/workflows/cicd-app.yml
      - FrontEnd/**
      - BackEnd/**
      - Deployment/**

jobs:
  # Build frontend application
  build-frontend-app:
    name: Build frontend application
    runs-on: ubuntu-latest
    env:
      PROJECT_DIRECTORY: ./FrontEnd
      BUILD_CONFIGURATION: ${{ github.ref_name == 'main' && 'production' || 'testing' }}
      BUILD_DIRECTORY: ./FrontEnd/dist
    steps:
      # Checkout the repository
      - uses: actions/checkout@v3
        name: Checkout repository
        with:
          submodules: true

      # Setup Node environment
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      # Install Angular CLI globally
      - name: Install Angular CLI
        run: npm install -g @angular/cli

      # Install dependencies
      - name: Install project dependencies
        working-directory: ${{ env.PROJECT_DIRECTORY }}
        run: npm install

      # Build the client
      - name: Build client application
        working-directory: ${{ env.PROJECT_DIRECTORY }}
        run: ng build --configuration $BUILD_CONFIGURATION

      # Copy static web app config
      - name: Copy static web app config
        run: cp $PROJECT_DIRECTORY/staticwebapp.config.json $BUILD_DIRECTORY

      # Upload build artifact
      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: frontend-app
          path: ${{ env.BUILD_DIRECTORY }}

  # Build backend application
  build-backend-app:
    name: Build backend application
    uses: ./.github/workflows/build-backend-app.yml

  # Deploy shared infrastructure
  deploy-shared-infra:
    name: Deploy shared infrastructure
    uses: ./.github/workflows/deploy-shared-infra.yml
    if: github.event_name != 'pull_request'
    secrets: inherit

  # Deploy application infrastructure
  deploy-app-infra:
    name: Deploy application infrastructure
    if: github.event_name != 'pull_request'
    needs:
      - build-frontend-app
      - build-backend-app
      - deploy-shared-infra
    uses: ./.github/workflows/deploy-app-infra.yml
    with:
      environment: ${{ github.ref_name == 'main' && 'prod' || 'test' }}
      database-throughput: ${{ github.ref_name == 'main' && 600 || 400 }}
    secrets:
      client-id: ${{ secrets.AZURE_CLIENT_ID }}
      tenant-id: ${{ secrets.AZURE_TENANT_ID }}
      subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

  # Deploy frontend application
  deploy-frontend-app:
    name: Deploy frontend application
    runs-on: ubuntu-latest
    needs: deploy-app-infra
    environment: ${{ github.ref_name == 'main' && 'prod' || 'test' }}
    permissions:
      id-token: write
    env:
      APP_PATH: "${{ github.workspace }}/app"

    steps:
      # Login to Azure
      - uses: azure/login@v1
        name: Login to Azure
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      # Download application artifact
      - name: Download application artifact
        uses: actions/download-artifact@v3
        with:
          name: frontend-app
          path: ${{ env.APP_PATH }}

      # Deploy application
      - uses: azure/static-web-apps-deploy@v1
        name: Deploy application
        with:
          action: upload
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          app_location: ${{ env.APP_PATH }}
          skip_app_build: true
          skip_api_build: true

  # Deploy backend application
  deploy-backend-app:
    name: Deploy backend application
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request'
    needs: deploy-app-infra
    environment: ${{ github.ref_name == 'main' && 'prod' || 'test' }}
    permissions:
      id-token: write
    env:
      APP_NAME: ${{ github.ref_name == 'main' && 'app-ohmyword-prod' || 'app-ohmyword-test' }}
    steps:
      # Login to Azure
      - uses: azure/login@v1
        name: Login to Azure
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      # Download application artifact
      - name: Download application artifact
        uses: actions/download-artifact@v3
        with:
          name: backend-app

      # Deploy to Azure app service
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.APP_NAME }}
