name: CI/CD Functions

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/cicd-functions.yml
      - Functions/**
      - ./Deployment/Infrastructure/functions/**
  pull_request:
    branches:
      - main
    paths:
      - .github/workflows/cicd-functions.yml
      - Functions/**
      - ./Deployment/Infrastructure/functions/**

jobs:
  # Build and publish functions application
  build-publish:
    name: Build and publish
    runs-on: ubuntu-latest
    env:
      PROJECT_DIRECTORY: ./Functions
      BUILD_CONFIGURATION: Release
      PUBLISH_DIRECTORY: /tmp/app
    steps:
      # Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Build project
      - name: Build solution
        working-directory: ${{ env.PROJECT_DIRECTORY }}
        run: dotnet build --configuration $BUILD_CONFIGURATION --output $PUBLISH_DIRECTORY

      # Upload published application artifact
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: functions-app
          path: ${{ env.PUBLISH_DIRECTORY }}

  # Deploy shared infrastructure
  deploy-shared-infra:
    name: Deploy shared infrastructure
    uses: ./.github/workflows/deploy-shared-infra.yml
    if: github.event_name != 'pull_request'
    secrets: inherit

  # Deploy functions infrastructure
  deploy-functions-infra:
    name: Deploy functions infrastructure
    runs-on: ubuntu-latest
    environment: shared
    needs: deploy-shared-infra
    permissions:
      id-token: write
    env:
      TEMPLATE_ROOT: ${{ github.workspace }}/templates
    steps:
      # Download application artifact
      - name: Download application artifact
        uses: actions/download-artifact@v3
        with:
          name: infra-templates
          path: ${{ env.TEMPLATE_ROOT }}

      # Login to Azure
      - uses: azure/login@v1
        name: Login to Azure
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      # Deploy functions infrastructure
      - uses: azure/arm-deploy@v1
        name: Deploy infrastructure
        with:
          resourceGroupName: rg-ohmyword-functions
          template: ${{ env.TEMPLATE_ROOT }}/functions/main.bicep
          parameters: ${{ env.TEMPLATE_ROOT }}/functions/main.parameters.json

  # Deploy functions application
  deploy-functions-app:
    name: Deploy functions application
    runs-on: ubuntu-latest
    environment: shared
    needs:
      - build-publish
      - deploy-functions-infra
    env:
      PACKAGE_DIRECTORY: ./package
    steps:
      # Download application artifact
      - name: Download application artifact
        uses: actions/download-artifact@v3
        with:
          name: functions-app
          path: ${{ env.PACKAGE_DIRECTORY }}

      # Publish functions application
      - name: Publish functions application
        uses: Azure/functions-action@v1
        with:
          app-name: func-ohmyword-functions
          package: ${{ env.PACKAGE_DIRECTORY }}
          publish-profile: ${{ secrets.AZURE_FUNCTIONS_PUBLISH_PROFILE }}
