name: CI/CD FrontEnd

on:
  push:
    branches:
      - develop
    paths:
      - .github/workflows/cicd-frontend.yml
      - FrontEnd/**

jobs:
  build:
    name: Build and deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Checkout repository
        with:
          submodules: true