name: CI/CD Application

on:
  push:
    branches:
      - main
      - develop
    paths:
      - .github/workflows/cicd-app.yml
      - FrontEnd/**
      - BackEnd/**
      - Deployment/**

  pull_request:
    branches:
      - main
    paths:
      - .github/workflows/cicd-app.yml
      - FrontEnd/**
      - BackEnd/**
      - Deployment/**

jobs:
  # Build backend applications
  build-backend-apps:
    name: Build backend applications
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.ref_name == 'main' && 'prod' || 'test' }}
    env:
      BACKEND_DIRECTORY: ${{ github.workspace }}/BackEnd
      BUILD_CONFIGURATION: Release
      PUBLISH_RUNTIME: linux-x64
      API_PUBLISH_DIRECTORY: ${{ github.workspace }}/publish/api
      FUNCTIONS_PUBLISH_DIRECTORY: ${{ github.workspace }}/publish/functions
    steps:
      # Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Cache packages
      - name: Cache packages
        uses: actions/cache@v3
        env:
          cache-name: nuget
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-${{ env.cache-name }}-

      # Restore packages
      - name: Restore packages
        run: dotnet restore --locked-mode
        working-directory: ${{ env.BACKEND_DIRECTORY }}

      # Build solution
      - name: Build solution
        run: dotnet build --no-restore --configuration $BUILD_CONFIGURATION
        working-directory: ${{ env.BACKEND_DIRECTORY }}

      # Run unit tests
      - name: Run unit tests
        run: dotnet test --no-build --configuration $BUILD_CONFIGURATION --filter Category=Unit
        working-directory: ${{ env.BACKEND_DIRECTORY }}

      # Run integration tests
      - name: Run integration tests
        if: ${{ vars.RUN_INTEGRATION_TESTS == 'true' }}
        run: dotnet test --no-build --configuration $BUILD_CONFIGURATION --filter Category=Integration
        working-directory: ${{ env.BACKEND_DIRECTORY }}
        env:
          OhMyWord_RapidApi__ApiKey: ${{ secrets.RAPID_API_KEY }}
          OhMyWord_GraphApiClient__ClientSecret: ${{ secrets.GRAPH_API_CLIENT_SECRET }}

      # Publish API
      - name: Publish API
        working-directory: ${{ env.BACKEND_DIRECTORY }}/Api
        run: >-
          dotnet publish
          --configuration $BUILD_CONFIGURATION
          --runtime $PUBLISH_RUNTIME
          --self-contained false
          --output $API_PUBLISH_DIRECTORY/publish

      # Copy API Dockerfile
      - name: Copy API Dockerfile
        working-directory: ${{ env.BACKEND_DIRECTORY }}/Api
        run: cp Dockerfile $API_PUBLISH_DIRECTORY

      # Upload API artifact
      - name: Upload API artifact
        uses: actions/upload-artifact@v3
        with:
          name: backend-app
          path: ${{ env.API_PUBLISH_DIRECTORY }}

      # Publish Functions
      - name: Publish Functions
        working-directory: ${{ env.BACKEND_DIRECTORY }}/Functions
        run: >-
          dotnet publish
          --configuration $BUILD_CONFIGURATION
          --runtime $PUBLISH_RUNTIME
          --self-contained false
          --output $FUNCTIONS_PUBLISH_DIRECTORY

      # Upload Functions artifact
      - name: Upload Functions artifact
        uses: actions/upload-artifact@v3
        with:
          name: functions-app
          path: ${{ env.FUNCTIONS_PUBLISH_DIRECTORY }}

  # Deploy Functions application
  deploy-functions-app:
    name: Deploy Functions application
    runs-on: ubuntu-latest
    needs:
      - build-backend-apps
    env:
      APP_PATH: ${{ github.workspace }}/app
    steps:
      # Download application artifact
      - name: Download application artifact
        uses: actions/download-artifact@v3
        with:
          name: functions-app
          path: ${{ env.APP_PATH }}

      # Publish functions application
      - name: Publish functions application
        uses: Azure/functions-action@v1
        with:
          app-name: ohmyword-functions
          package: ${{ env.APP_PATH }}
          publish-profile: ${{ secrets.AZURE_FUNCTIONS_PUBLISH_PROFILE }}

  # Deploy backend application
  deploy-backend-app:
    name: Deploy backend application
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request'
    needs:
      - build-backend-apps
    environment: ${{ github.ref_name == 'main' && 'prod' || 'test' }}
    permissions:
      id-token: write
    env:
      APP_PATH: ${{ github.workspace }}/app
    steps:
      # Download application artifact
      - name: Download application artifact
        uses: actions/download-artifact@v3
        with:
          name: backend-app
          path: ${{ env.APP_PATH }}

      # Login to Azure
      - uses: azure/login@v1
        name: Login to Azure
        with:
          client-id: ${{ vars.AZURE_CLIENT_ID }}
          tenant-id: ${{ vars.AZURE_TENANT_ID }}
          subscription-id: ${{ vars.AZURE_SUBSCRIPTION_ID }}

      # Build and deploy Container App
      - name: Build and deploy Container App
        uses: azure/container-apps-deploy-action@v1
        env:
          IMAGE_NAME: ohmyword-api
          IMAGE_TAG: ${{ github.ref_name == 'main' && 'prod' || 'test' }}
          CONTAINER_REGISTRY: snakebyte
          CONTAINER_APP_NAME: ohmyword-${{ github.ref_name == 'main' && 'prod' || 'test' }}-ca
          RESOURCE_GROUP: ohmyword-${{ github.ref_name == 'main' && 'prod' || 'test' }}
        with:
          appSourcePath: ${{ env.APP_PATH }}
          acrName: ${{ env.CONTAINER_REGISTRY }}
          imageToBuild: ${{ env.CONTAINER_REGISTRY }}.azurecr.io/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
          containerAppName: ${{ env.CONTAINER_APP_NAME }}
          resourceGroup: ${{ env.RESOURCE_GROUP }}
