name: CI/CD Functions

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/cicd-functions.yml
      - Functions/**
      - ./Deployment/Infrastructure/functions/**
  pull_request:
    branches:
      - main
    paths:
      - .github/workflows/cicd-functions.yml
      - Functions/**
      - ./Deployment/Infrastructure/shared/**

jobs:
  # Build and publish functions application
  build-publish:
    name: Build and publish
    runs-on: ubuntu-latest
    env:
      PROJECT_DIRECTORY: ./Functions
      BUILD_CONFIGURATION: Release
      PUBLISH_DIRECTORY: ${{ github.workspace }}/app
    steps:
      # Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Build project
      - name: Build solution
        working-directory: ${{ env.PROJECT_DIRECTORY }}
        run: dotnet build --configuration $BUILD_CONFIGURATION --output $PUBLISH_DIRECTORY

      # Upload published application artifact
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: functions-app
          path: ${{ env.PUBLISH_DIRECTORY }}

  # Deploy shared infrastructure
  deploy-shared-infra:
    name: Deploy shared infrastructure
    uses: ./.github/workflows/deploy-shared-infra.yml
    if: github.event_name != 'pull_request'
    with:
      environment: prod
      resourceGroupName: rg-ohmyword-shared
    secrets: inherit

  # Deploy functions application
  deploy-functions-app:
    name: Deploy functions application
    runs-on: ubuntu-latest
    environment: prod
    needs:
      - build-publish
      - deploy-shared-infra
    env:
      PACKAGE_DIRECTORY: ${{ github.workspace }}/app
    steps:
      # Download application artifact
      - name: Download application artifact
        uses: actions/download-artifact@v3
        with:
          name: functions-app
          path: ${{ env.PACKAGE_DIRECTORY }}

      # Publish functions application
      - name: Publish functions application
        uses: Azure/functions-action@v1
        with:
          app-name: func-ohmyword-functions
          package: ${{ env.PACKAGE_DIRECTORY }}
          publish-profile: ${{ secrets.AZURE_FUNCTIONS_PUBLISH_PROFILE }}
