name: CI/CD FrontEnd

on:
  push:
    branches:
      - develop
    paths:
      - .github/workflows/cicd-frontend.yml
      - FrontEnd/**

jobs:
  build:
    name: Build and deploy
    runs-on: ubuntu-latest
    environment: Test
    permissions:
      id-token: write
    steps:
      # Checkout the repository
      - uses: actions/checkout@v3
        name: Checkout repository
        with:
          submodules: true
      # Login to Azure
      - uses: azure/login@v1
        name: Login to Azure
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      # Deploy infrastructure
      - uses: azure/arm-deploy@v1
        name: Deploy infrastructure
        with:
          resourceGroupName: rg-ohmyword
          template: ./Deployment/Infrastructure/frontend.bicep
