name: CI/CD

on:
  push:
    branches:
      - main
      - develop
    paths:
      - .github/workflows/cicd.yml
      - FrontEnd/**
      - BackEnd/**
      - Deployment/**

jobs:
  # Build the frontend application
  build-frontend:
    runs-on: ubuntu-latest
    name: Build Frontend
    steps:
      # Checkout the repository
      - uses: actions/checkout@v3
        name: Checkout repository
        with:
          submodules: true

      # Setup Node environment
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      # Install dependencies
      - name: Install dependencies
        working-directory: ./FrontEnd
        run: npm ci

      # Build the client
      - name: Build client application
        working-directory: ./FrontEnd
        run: npm run build

      # Upload build artifact
      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: frontend-app
          path: ./FrontEnd/dist

  build-backend:
    runs-on: ubuntu-latest
    name: Build Backend
    steps:
      # Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          lfs: true

      # Setup .NET environment
      - name: Set up .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x'

      # Build solution
      - name: Build solution
        run: dotnet build --configuration Release

      # Test solution
      - name: Test solution
        run: dotnet test --configuration Release

      # Publish application
      - name: Publish application
        working-directory: ./Api
        run: dotnet publish --configuration Release --output ${{env.DOTNET_ROOT}}/app

      # Upload published application artifact
      - name: Upload published application artifact
        uses: actions/upload-artifact@v3
        with:
          name: backend-app
          path: ${{env.DOTNET_ROOT}}/app
