name: CI/CD Application

on:
  push:
    branches:
      - main
      - develop
    paths:
      - .github/workflows/cicd-app.yml
      - FrontEnd/**
      - BackEnd/**
      - Deployment/**

  pull_request:
    branches:
      - main
    paths:
      - .github/workflows/cicd-app.yml
      - FrontEnd/**
      - BackEnd/**
      - Deployment/**

jobs:
  # Build frontend application
  build-frontend-app:
    name: Build frontend application
    runs-on: ubuntu-latest
    env:
      PROJECT_DIRECTORY: ./FrontEnd
      BUILD_CONFIGURATION: ${{ github.ref_name == 'main' && 'production' || 'testing' }}
      BUILD_DIRECTORY: ./FrontEnd/dist
    steps:
      # Checkout the repository
      - uses: actions/checkout@v3
        name: Checkout repository
        with:
          submodules: true

      # Setup Node environment
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      # Cache node modules
      - name: Cache node modules
        uses: actions/cache@v3
        env:
          cache-name: npm
        with:
          path: ~/.npm
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-${{ env.cache-name }}-

      # Install Angular CLI globally
      - name: Install Angular CLI
        run: npm install -g @angular/cli

      # Install dependencies
      - name: Install project dependencies
        working-directory: ${{ env.PROJECT_DIRECTORY }}
        run: npm install

      # Build the client
      - name: Build client application
        working-directory: ${{ env.PROJECT_DIRECTORY }}
        run: ng build --configuration $BUILD_CONFIGURATION

      # Copy static web app config
      - name: Copy static web app config
        run: cp $PROJECT_DIRECTORY/staticwebapp.config.json $BUILD_DIRECTORY

      # Upload build artifact
      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: frontend-app
          path: ${{ env.BUILD_DIRECTORY }}

  # Build backend application
  build-backend-app:
    name: Build backend application
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.ref_name == 'main' && 'prod' || 'test' }}
    env:
      BUILD_CONFIGURATION: Release
      PUBLISH_OS: linux
      PUBLISH_DIRECTORY: ${{ github.workspace }}/app
    steps:
      # Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Cache packages
      - name: Cache packages
        uses: actions/cache@v3
        env:
          cache-name: nuget
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-${{ env.cache-name }}-

      # Restore packages
      - name: Restore packages
        run: dotnet restore --locked-mode

      # Build solution
      - name: Build solution
        run: dotnet build --no-restore --configuration $BUILD_CONFIGURATION

      # Run tests
      - name: Run tests
        run: dotnet test --no-build --configuration $BUILD_CONFIGURATION
        env:
          OhMyWord_RapidApi__ApiKey: ${{ secrets.RAPID_API_KEY }}
          OhMyWord_GraphApiClient__ClientSecret: ${{ secrets.GRAPH_API_CLIENT_SECRET }}

      # Publish application
      - name: Publish application
        working-directory: ./BackEnd/Api
        run: dotnet publish --configuration $BUILD_CONFIGURATION --os $PUBLISH_OS --output $PUBLISH_DIRECTORY

      # Delete app settings file
      - name: Remove development settings
        run: rm $PUBLISH_DIRECTORY/appsettings.Development.json

      # Upload published application artifact
      - name: Upload published application artifact
        uses: actions/upload-artifact@v3
        with:
          name: backend-app
          path: ${{ env.PUBLISH_DIRECTORY }}

  # Deploy shared infrastructure
  deploy-shared-infra:
    name: Deploy shared infrastructure
    uses: ./.github/workflows/deploy-shared-infra.yml
    if: github.event_name != 'pull_request'
    with:
      environment: ${{ github.ref_name == 'main' && 'prod' || 'test' }}
      resourceGroupName: rg-ohmyword-shared
      tenant-id: ${{ vars.AZURE_TENANT_ID }}
      subscription-id: ${{ vars.AZURE_SUBSCRIPTION_ID }}
      client-id: ${{ vars.AZURE_CLIENT_ID }}

  # Deploy Functions application
  deploy-functions-app:
    name: Deploy Functions application
    uses: ./.github/workflows/deploy-functions-app.yml
    needs: deploy-shared-infra
    secrets:
      PUBLISH_PROFILE: ${{ secrets.AZURE_FUNCTIONS_PUBLISH_PROFILE }}

  # Deploy application infrastructure
  deploy-app-infra:
    name: Deploy application infrastructure
    if: github.event_name != 'pull_request'
    needs:
      - build-frontend-app
      - build-backend-app
      - deploy-shared-infra
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name == 'main' && 'prod' || 'test' }}
    permissions:
      id-token: write
    env:
      TEMPLATE_ROOT: ${{ github.workspace }}/templates
      RESOURCE_GROUP_NAME: rg-ohmyword-${{ github.ref_name == 'main' && 'prod' || 'test' }}
      APPLICATION_ENVIRONMENT: ${{ github.ref_name == 'main' && 'prod' || 'test' }}
    steps:
      # Download application artifact
      - name: Download application artifact
        uses: actions/download-artifact@v3
        with:
          name: infra-templates
          path: ${{ env.TEMPLATE_ROOT }}

      # Login to Azure
      - uses: azure/login@v1
        name: Login to Azure
        with:
          client-id: ${{ vars.AZURE_CLIENT_ID }}
          tenant-id: ${{ vars.AZURE_TENANT_ID }}
          subscription-id: ${{ vars.AZURE_SUBSCRIPTION_ID }}

      # Deploy infrastructure
      - uses: azure/arm-deploy@v1
        name: Deploy infrastructure
        with:
          scope: resourcegroup
          resourceGroupName: ${{ env.RESOURCE_GROUP_NAME }}
          template: ${{ env.TEMPLATE_ROOT }}/app/main.bicep
          parameters: ${{ env.TEMPLATE_ROOT }}/app/${{ env.APPLICATION_ENVIRONMENT }}.bicepparam

  # Deploy frontend application
  deploy-frontend-app:
    name: Deploy frontend application
    runs-on: ubuntu-latest
    needs: deploy-app-infra
    environment:
      name: ${{ github.ref_name == 'main' && 'prod' || 'test' }}
      url: ${{ github.ref_name == 'main' && 'https://ohmyword.live' || 'https://test.ohmyword.live' }}
    permissions:
      id-token: write
    env:
      APP_PATH: ${{ github.workspace }}/app
    steps:
      # Login to Azure
      - uses: azure/login@v1
        name: Login to Azure
        with:
          client-id: ${{ vars.AZURE_CLIENT_ID }}
          tenant-id: ${{ vars.AZURE_TENANT_ID }}
          subscription-id: ${{ vars.AZURE_SUBSCRIPTION_ID }}

      # Download application artifact
      - name: Download application artifact
        uses: actions/download-artifact@v3
        with:
          name: frontend-app
          path: ${{ env.APP_PATH }}

      # Deploy application
      - uses: azure/static-web-apps-deploy@v1
        name: Deploy application
        with:
          action: upload
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          app_location: ${{ env.APP_PATH }}
          skip_app_build: true
          skip_api_build: true

  # Deploy backend application
  deploy-backend-app:
    name: Deploy backend application
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request'
    needs: deploy-app-infra
    environment: ${{ github.ref_name == 'main' && 'prod' || 'test' }}
    permissions:
      id-token: write
    env:
      APP_NAME: ${{ github.ref_name == 'main' && 'app-ohmyword-prod' || 'app-ohmyword-test' }}
    steps:
      # Login to Azure
      - uses: azure/login@v1
        name: Login to Azure
        with:
          client-id: ${{ vars.AZURE_CLIENT_ID }}
          tenant-id: ${{ vars.AZURE_TENANT_ID }}
          subscription-id: ${{ vars.AZURE_SUBSCRIPTION_ID }}

      # Download application artifact
      - name: Download application artifact
        uses: actions/download-artifact@v3
        with:
          name: backend-app

      # Deploy to Azure app service
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.APP_NAME }}
