name: Deploy infrastructure

on:
  workflow_call:
    inputs:
      environment:
        type: string
        required: true
      resource-group:
        type: string
        required: true
      template-file:
        type: string
        required: true

permissions:
  id-token: write
  contents: read

jobs:
  deploy-infrastructure:
    name: Infrastructure
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      # Login to Azure
      - uses: azure/login@v1
        name: Login to Azure
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      # Check out the repository
      - uses: actions/checkout@v3
        name: Checkout repository
        with:
          lfs: true

      # Deploy Bicep template
      - name: Deploy Bicep template
        working-directory: ./Infrastructure
        run: az deployment group create --resource-group ${{ inputs.resource-group }} --template-file ${{ inputs.template-file }}
