on: workflow_call

jobs:
  deploy:
    name: Deploy functions infrastructure
    runs-on: ubuntu-latest
    needs: deploy-shared-infra
    if: github.event_name != 'pull_request'
    environment: ${{ github.ref_name == 'main' && 'prod' || 'test' }}
    permissions:
      id-token: write
    env:
      BUILD_CONFIGURATION: Release
      RESOURCE_GROUP_NAME: rg-ohmyword-functions
      AZURE_FUNCTIONAPP_NAME: func-ohmyword-functions
      AZURE_FUNCTIONAPP_PACKAGE_PATH: ./BackEnd/Functions
      DOTNET_VERSION: 7.0.x
    steps:
      # Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Login to Azure
      - uses: azure/login@v1
        name: Login to Azure
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      # Deploy functions infrastructure
      - uses: azure/arm-deploy@v1
        name: Deploy infrastructure
        with:
          resourceGroupName: ${{ env.RESOURCE_GROUP_NAME }}
          template: ./Deployment/Infrastructure/functions/main.bicep
          parameters: ./Deployment/Infrastructure/functions/main.parameters.json
