on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
    secrets:
      client-id:
        required: true
      tenant-id:
        required: true
      subscription-id:
        required: true

jobs:
  deploy-app-infra:
    name: Deploy application infrastructure
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    permissions:
      id-token: write
    env:
      RESOURCE_GROUP_NAME: rg-ohmyword-${{ inputs.environment }}
    steps:
      # Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Login to Azure
      - uses: azure/login@v1
        name: Login to Azure
        with:
          client-id: ${{ secrets.client-id }}
          tenant-id: ${{ secrets.tenant-id }}
          subscription-id: ${{ secrets.subscription-id }}

      # Deploy infrastructure
      - uses: azure/arm-deploy@v1
        name: Deploy infrastructure
        env:
          DATABASE_THROUGHPUT: ${{ inputs.environment == 'prod' && '600' || '400' }}
        with:
          resourceGroupName: ${{ env.RESOURCE_GROUP_NAME }}
          template: ./Deployment/Infrastructure/app/main.bicep
          parameters: >-
            ./Deployment/Infrastructure/app/main.parameters.json
            appEnv=${{ inputs.environment }}
            databaseThroughput=${{ env.DATABASE_THROUGHPUT }}
