name: Deploy API

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build application
    runs-on: ubuntu-latest
    steps:
      # Check out the repository 
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          lfs: true
      
      # Setup .NET environment
      - name: Set up .NET Core
        uses: actions/setup-dotnet@v2
        with: 
          dotnet-version: '6.0.x'
      
      # Restore packages
      - name: Restore packages
        run: dotnet restore

      # Build API project
      - name: Build solution
        run: dotnet build --no-restore --configuration Release ./Api/Api.csproj

      # Publish API project
      - name: Publish API project
        run: dotnet publish --no-build --output ${{env.DOTNET_ROOT}}/api ./Api/Api.csproj

      # Upload API project artifact
      - name: Upload API project artifact
        uses: actions/upload-artifact@v2
        with:
          name: published-api
          path: ${{env.DOTNET_ROOT}}/api
