on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

jobs:
  deploy-shared-infra:
    name: Deploy shared infrastructure
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request'
    environment: ${{ inputs.environment }}
    permissions:
      id-token: write
    steps:
      # Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Login to Azure
      - uses: azure/login@v1
        name: Login to Azure
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      # Deploy shared infrastructure
      - uses: azure/arm-deploy@v1
        name: Deploy shared infrastructure
        with:
          resourceGroupName: rg-ohmyword-shared
          template: ./Deployment/Infrastructure/shared/main.bicep
          parameters: >-
            ./Deployment/Infrastructure/shared/main.parameters.json
            dictionaryApiKey=${{ secrets.DICTIONARY_API_KEY }}
            thesaurusApiKey=${{ secrets.THESAURUS_API_KEY }}
