name: Deploy shared infrastructure

on:
  workflow_call:
    inputs:
      environment:
        description: The name of the environment to deploy to
        required: true
        type: string
      resourceGroupName:
        description: The name of the resource group to deploy to
        required: true
        type: string
      tenant-id:
        description: Azure tenant ID
        required: true
        type: string
      subscription-id:
        description: Azure subscription ID
        required: true
        type: string
      client-id:
        description: Azure client ID
        required: true
        type: string  

jobs:
  deploy:
    name: Deploy template
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    env:
      TEMPLATE_ROOT: ./Deployment/Infrastructure
    permissions:
      id-token: write
    steps:
      # Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Login to Azure
      - uses: azure/login@v1
        name: Login to Azure
        with:
          client-id: ${{ inputs.client-id }}
          tenant-id: ${{ inputs.tenant-id }}
          subscription-id: ${{ inputs.subscription-id }}

      # Deploy shared infrastructure
      - uses: azure/arm-deploy@v1
        name: Deploy shared infrastructure
        with:
          resourceGroupName: ${{ inputs.resourceGroupName }}
          template: ${{ env.TEMPLATE_ROOT }}/shared/main.bicep
          scope: resourcegroup
          parameters: >-
            ${{ env.TEMPLATE_ROOT }}/shared/main.parameters.json

      # Upload published application artifact
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        env:
          TEMPLATE_ROOT: ./Deployment/Infrastructure
        with:
          name: infra-templates
          path: ${{ env.TEMPLATE_ROOT }}
