on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
    secrets:
      client-id:
        required: true
      tenant-id:
        required: true
      subscription-id:
        required: true

jobs:
  deploy:
    name: Deploy functions infrastructure
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    permissions:
      id-token: write
    env:
      TEMPLATE_ROOT: ${{ github.workspace }}/templates
      RESOURCE_GROUP_NAME: rg-ohmyword-functions
    steps:
      # Download application artifact
      - name: Download application artifact
        uses: actions/download-artifact@v3
        with:
          name: infra-templates
          path: ${{ env.TEMPLATE_ROOT }}

      # Login to Azure
      - uses: azure/login@v1
        name: Login to Azure
        with:
          client-id: ${{ secrets.client-id }}
          tenant-id: ${{ secrets.tenant-id }}
          subscription-id: ${{ secrets.subscription-id }}

      # Deploy functions infrastructure
      - uses: azure/arm-deploy@v1
        name: Deploy infrastructure
        with:
          resourceGroupName: ${{ env.RESOURCE_GROUP_NAME }}
          template: ${{ env.TEMPLATE_ROOT }}/functions/main.bicep
          parameters: ${{ env.TEMPLATE_ROOT }}/functions/main.parameters.json
