name: Deploy Client

on:
  push:
    branches:
      - main
    paths:
      - Client/**

jobs:
  build_and_deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      # Check out the repository using LFS
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          lfs: true

      # Build and deploy using Azure Static Web Apps - Configuration information https://aka.ms/swaworkflowconfig
      - name: Build and Deploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_SWA_DEPLOYMENT_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: upload
          app_location: Client
          output_location: dist
