on: workflow_call

jobs:
  # Deploy shared infrastructure
  deploy-shared-infra:
    name: Deploy shared template
    runs-on: ubuntu-latest
    environment: shared
    env:
      TEMPLATE_ROOT: ./Deployment/Infrastructure
    permissions:
      id-token: write
    steps:
      # Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Login to Azure
      - uses: azure/login@v1
        name: Login to Azure
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      # Deploy shared infrastructure
      - uses: azure/arm-deploy@v1
        name: Deploy shared infrastructure
        with:
          resourceGroupName: rg-ohmyword-shared
          template: ${{ env.TEMPLATE_ROOT }}/shared/main.bicep
          parameters: >-
            ${{ env.TEMPLATE_ROOT }}/shared/main.parameters.json
            dictionaryApiKey=${{ secrets.DICTIONARY_API_KEY }}
            thesaurusApiKey=${{ secrets.THESAURUS_API_KEY }}

      # Upload published application artifact
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        env:
          TEMPLATE_ROOT: ./Deployment/Infrastructure
        with:
          name: infra-templates
          path: ${{ env.TEMPLATE_ROOT }}
