name: Deploy API

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build application
    runs-on: ubuntu-latest
    steps:
      # Check out the repository 
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          lfs: true
      
      # Setup .NET environment
      - name: Set up .NET Core
        uses: actions/setup-dotnet@v2
        with: 
          dotnet-version: '6.0.x'
          include-prerelease: true

      # Build solution
      - name: Build solution
        run: dotnet build --configuration Release

      # Publish API project
      - name: Publish API project
        run: dotnet publish --configuration Release --output ${{env.DOTNET_ROOT}}/api Api

      # Upload API project artifact
      - name: Upload API project artifact
        uses: actions/upload-artifact@v3
        with:
          name: published-api
          path: ${{env.DOTNET_ROOT}}/api
