on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
    secrets:
      client-id:
        required: true
      tenant-id:
        required: true
      subscription-id:
        required: true
      dictionary-api-key:
        required: true
      thesaurus-api-key:
        required: true

jobs:
  deploy-shared-infra:
    name: Deploy template
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    permissions:
      id-token: write
    steps:
      # Download application artifact
      - name: Download application artifact
        uses: actions/download-artifact@v3
        with:
          name: infra-templates

      # Login to Azure
      - uses: azure/login@v1
        name: Login to Azure
        with:
          client-id: ${{ secrets.client-id }}
          tenant-id: ${{ secrets.tenant-id }}
          subscription-id: ${{ secrets.subscription-id }}

      # Deploy shared infrastructure
      - uses: azure/arm-deploy@v1
        name: Deploy shared infrastructure
        with:
          resourceGroupName: rg-ohmyword-shared
          template: ./infra-templates/shared/main.bicep
          parameters: >-
            ./Deployment/Infrastructure/shared/main.parameters.json
            dictionaryApiKey=${{ secrets.dictionary-api-key }}
            thesaurusApiKey=${{ secrets.thesaurus-api-key }}
