name: Deploy Functions App

on:
  workflow_call:
    secrets:
      PUBLISH_PROFILE:
        description: Publish profile for the Functions App
        required: true

jobs:
  # Build and publish functions application
  build-publish:
    name: Build and publish
    runs-on: ubuntu-latest
    env:
      PROJECT_DIRECTORY: ./Functions
      BUILD_CONFIGURATION: Release
      PUBLISH_DIRECTORY: ${{ github.workspace }}/app
    steps:
      # Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Build project
      - name: Build solution
        working-directory: ${{ env.PROJECT_DIRECTORY }}
        run: dotnet build --configuration $BUILD_CONFIGURATION --output $PUBLISH_DIRECTORY

      # Publish functions application
      - name: Publish functions application
        uses: Azure/functions-action@v1
        with:
          app-name: func-ohmyword-functions
          package: ${{ env.PUBLISH_DIRECTORY }}
          publish-profile: ${{ secrets.PUBLISH_PROFILE }}
