on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
    secrets:
      client-id:
        required: true
      tenant-id:
        required: true
      subscription-id:
        required: true
      dictionary-api-key:
        required: true
      thesaurus-api-key:
        required: true

jobs:
  deploy-shared-infra:
    name: Deploy shared infrastructure
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request'
    environment: ${{ inputs.environment }}
    permissions:
      id-token: write
    steps:
      # Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Login to Azure
      - uses: azure/login@v1
        name: Login to Azure
        with:
          client-id: ${{ secrets.client-id }}
          tenant-id: ${{ secrets.tenant-id }}
          subscription-id: ${{ secrets.subscription-id }}

      # Deploy shared infrastructure
      - uses: azure/arm-deploy@v1
        name: Deploy shared infrastructure
        with:
          resourceGroupName: rg-ohmyword-shared
          template: ./Deployment/Infrastructure/shared/main.bicep
          parameters: >-
            ./Deployment/Infrastructure/shared/main.parameters.json
            dictionaryApiKey=${{ secrets.dictionary-api-key }}
            thesaurusApiKey=${{ secrets.thesaurus-api-key }}
