name: Publish application

on:
  workflow_call:
    inputs:
      environment:
        type: string
        required: true
      app-name:
        type: string
        required: true
    secrets:
      client-id:
        required: true
      tenant-id:
        required: true
      subscription-id:
        required: true

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    name: Deploy to Azure
    runs-on: ubuntu-latest
    steps:
       # Login to Azure
      - uses: azure/login@v1
        name: Login to Azure
        with:
          client-id: ${{ secrets.client-id }}
          tenant-id: ${{ secrets.tenant-id }}
          subscription-id: ${{ secrets.subscription-id }}
      
      # Download published application from build job
      - name: Download published application artifact
        uses: actions/download-artifact@v3
        with:
          name: published-app

      # Deploy to Azure app service
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ inputs.app-name }}
      